In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import MinMaxScaler

In [25]:
train = pd.read_csv('use_this.csv')
train.head()

,stn4contest,v01,v02,v03,v04,v05,v06,v07,v08,v09,vv,class_interval,year,month,day,hour
0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,5,1,12
1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,5,1,15
2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,5,1,18
3,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,5,1,21
4,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,5,2,0

In [10]:
# 학습 데이터와 테스트 데이터 분할
train_data = train[train['stn4contest'] <= 16]
test_data = train[train['stn4contest'] > 15]

# 입력 특성 (v01 ~ v09)와 타겟 변수 (vv) 분리
X_train = train_data[['stn4contest', 'year', 'month', 'day', 'hour', 'v01', 'v02', 'v03', 'v04', 'v05', 'v06', 'v07', 'v08', 'v09']]
y_train = train_data['vv']
X_test = test_data[['stn4contest', 'year', 'month', 'day', 'hour', 'v01', 'v02', 'v03', 'v04', 'v05', 'v06', 'v07', 'v08', 'v09']]
y_test = test_data['vv']

# 데이터 표준화
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# MLP 모델 정의
model = Sequential([
    Dense(64, input_dim=14, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation='linear')  # 회귀 문제이므로 선형 활성화 함수 사용
])

# 모델 컴파일
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

# 모델 학습
model.fit(X_train, y_train, epochs=50, batch_size=16, validation_split=0.2)

# 모델 예측
y_pred = model.predict(X_test)

# 성능 지표 계산
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# 결과 저장
results = {
    'Window Size': 1,  # 현재 예제에서는 window size가 1로 고정되어 있음
    'RMSE': rmse,
    'MAE': mae,
    'MSE': mse,
    'R²': r2
}

# 결과 출력
print("Model Performance Metrics by Window Size:")
print(f"{'Window Size':<15}{'RMSE':<10}{'MAE':<10}{'MSE':<10}{'R²':<10}")
print(f"{'-'*45}")
print(f"{results['Window Size']:<15}{results['RMSE']:<10.4f}{results['MAE']:<10.4f}{results['MSE']:<10.4f}{results['R²']:<10.4f}")

Epoch 1/50
3315/3315 [==============================] - 5s 1ms/step - loss: 12.0963 - mae: 0.9511 - val_loss: 15.8899 - val_mae: 0.8410
Epoch 2/50
3315/3315 [==============================] - 4s 1ms/step - loss: 11.5670 - mae: 0.8917 - val_loss: 14.7053 - val_mae: 0.9388
Epoch 3/50
3315/3315 [==============================] - 5s 1ms/step - loss: 11.4711 - mae: 0.8664 - val_loss: 14.9047 - val_mae: 0.8238
Epoch 4/50
3315/3315 [==============================] - 5s 1ms/step - loss: 11.4622 - mae: 0.8481 - val_loss: 14.7178 - val_mae: 1.0810
Epoch 5/50
3315/3315 [==============================] - 5s 1ms/step - loss: 11.4001 - mae: 0.8475 - val_loss: 14.6437 - val_mae: 0.8915
Epoch 6/50
3315/3315 [==============================] - 5s 1ms/step - loss: 11.4012 - mae: 0.8370 - val_loss: 14.7414 - val_mae: 0.8567
Epoch 7/50
3315/3315 [==============================] - 5s 1ms/step - loss: 11.3634 - mae: 0.8217 - val_loss: 14.4731 - val_mae: 0.9317
Epoch 8/50
3315/3315 [==============================] - 5s 1ms/step - loss: 11.3521 - mae: 0.8236 - val_loss: 14.4974 - val_mae: 0.8284
Epoch 9/50
3315/3315 [==============================] - 5s 2ms/step - loss: 11.3373 - mae: 0.8171 - val_loss: 14.9165 - val_mae: 0.9130
Epoch 10/50
3315/3315 [==============================] - 5s 1ms/step - loss: 11.3261 - mae: 0.8134 - val_loss: 14.8281 - val_mae: 0.8421
Epoch 11/50
3315/3315 [==============================] - 6s 2ms/step - loss: 11.3066 - mae: 0.8089 - val_loss: 15.2705 - val_mae: 0.7857
Epoch 12/50
3315/3315 [==============================] - 6s 2ms/step - loss: 11.2634 - mae: 0.8088 - val_loss: 14.5877 - val_mae: 0.8904
Epoch 13/50
3315/3315 [==============================] - 6s 2ms/step - loss: 11.3011 - mae: 0.8027 - val_loss: 14.6889 - val_mae: 0.8379
Epoch 14/50
3315/3315 [==============================] - 6s 2ms/step - loss: 11.2490 - mae: 0.8076 - val_loss: 15.2233 - val_mae: 0.8070
Epoch 15/50
3315/3315 [==============================] - 6s 2ms/step - loss: 11.2700 - mae: 0.8089 - val_loss: 14.7382 - val_mae: 0.8448
Epoch 16/50
3315/3315 [==============================] - 7s 2ms/step - loss: 11.2579 - mae: 0.8065 - val_loss: 14.9220 - val_mae: 0.8018
Epoch 17/50
3315/3315 [==============================] - 6s 2ms/step - loss: 11.2083 - mae: 0.8051 - val_loss: 15.5342 - val_mae: 0.8281
Epoch 18/50
3315/3315 [==============================] - 6s 2ms/step - loss: 11.2450 - mae: 0.8097 - val_loss: 14.8309 - val_mae: 0.8117
Epoch 19/50
3315/3315 [==============================] - 6s 2ms/step - loss: 11.1524 - mae: 0.8088 - val_loss: 14.7900 - val_mae: 0.8889
Epoch 20/50
3315/3315 [==============================] - 6s 2ms/step - loss: 11.2071 - mae: 0.8048 - val_loss: 14.9121 - val_mae: 0.8386
Epoch 21/50
3315/3315 [==============================] - 6s 2ms/step - loss: 11.1667 - mae: 0.8073 - val_loss: 15.0992 - val_mae: 0.8336
Epoch 22/50
3315/3315 [==============================] - 5s 2ms/step - loss: 11.1806 - mae: 0.8044 - val_loss: 14.9953 - val_mae: 0.8931
Epoch 23/50
3315/3315 [==============================] - 5s 2ms/step - loss: 11.1569 - mae: 0.8059 - val_loss: 15.0531 - val_mae: 0.7846
Epoch 24/50
3315/3315 [==============================] - 5s 2ms/step - loss: 11.0954 - mae: 0.8075 - val_loss: 14.9246 - val_mae: 0.8373
Epoch 25/50
3315/3315 [==============================] - 5s 2ms/step - loss: 11.1015 - mae: 0.8049 - val_loss: 14.5701 - val_mae: 0.8756
Epoch 26/50
3315/3315 [==============================] - 5s 2ms/step - loss: 11.1220 - mae: 0.8070 - val_loss: 14.5873 - val_mae: 0.9338
Epoch 27/50
3315/3315 [==============================] - 5s 2ms/step - loss: 11.1049 - mae: 0.8032 - val_loss: 14.6230 - val_mae: 0.8455
Epoch 28/50
3315/3315 [==============================] - 5s 2ms/step - loss: 11.0909 - mae: 0.8068 - val_loss: 15.2539 - val_mae: 0.8192
Epoch 29/50
3315/3315 [==============================] - 5s 2ms/step - loss: 11.0657 - mae: 0.8068 - val_loss: 14.8181 - val_mae: 0.8542
Epoch 30/50
3315/3315 [==============================] - 6s 2ms/step - loss: 11.0239 - mae: 0.8032 - val_loss: 14.8731 - val_mae: 0.8703
Epoch 31/50
3315/3315 [==============================] - 5s 2ms/step - loss: 11.0247 - mae: 0.8060 - val_loss: 15.7634 - val_mae: 0.8043
Epoch 32/50
3315/3315 [==============================] - 5s 2ms/step - loss: 11.0376 - mae: 0.7993 - val_loss: 15.0314 - val_mae: 0.8360
Epoch 33/50
3315/3315 [==============================] - 6s 2ms/step - loss: 10.9939 - mae: 0.8039 - val_loss: 14.7077 - val_mae: 0.9070
Epoch 34/50
3315/3315 [==============================] - 5s 2ms/step - loss: 10.9992 - mae: 0.8122 - val_loss: 14.8550 - val_mae: 0.8388
Epoch 35/50
3315/3315 [==============================] - 6s 2ms/step - loss: 10.9669 - mae: 0.8045 - val_loss: 14.7538 - val_mae: 0.8153
Epoch 36/50
3315/3315 [==============================] - 5s 2ms/step - loss: 10.9616 - mae: 0.8016 - val_loss: 14.8687 - val_mae: 0.8371
Epoch 37/50
3315/3315 [==============================] - 5s 2ms/step - loss: 10.9558 - mae: 0.8035 - val_loss: 15.4877 - val_mae: 0.8258
Epoch 38/50
3315/3315 [==============================] - 5s 2ms/step - loss: 10.9344 - mae: 0.8055 - val_loss: 14.8883 - val_mae: 0.8331
Epoch 39/50
3315/3315 [==============================] - 6s 2ms/step - loss: 10.9214 - mae: 0.8004 - val_loss: 14.8257 - val_mae: 0.8581
Epoch 40/50
3315/3315 [==============================] - 6s 2ms/step - loss: 10.9188 - mae: 0.8053 - val_loss: 14.5988 - val_mae: 0.8673
Epoch 41/50
3315/3315 [==============================] - 5s 2ms/step - loss: 10.8954 - mae: 0.8091 - val_loss: 15.0160 - val_mae: 0.8031
Epoch 42/50
3315/3315 [==============================] - 6s 2ms/step - loss: 10.8674 - mae: 0.8030 - val_loss: 14.9929 - val_mae: 0.9457
Epoch 43/50
3315/3315 [==============================] - 6s 2ms/step - loss: 10.8484 - mae: 0.8100 - val_loss: 15.4766 - val_mae: 0.8387
Epoch 44/50
3315/3315 [==============================] - 7s 2ms/step - loss: 10.8054 - mae: 0.8039 - val_loss: 14.5138 - val_mae: 0.8578
Epoch 45/50
3315/3315 [==============================] - 6s 2ms/step - loss: 10.8383 - mae: 0.8042 - val_loss: 15.1835 - val_mae: 0.8346
Epoch 46/50
3315/3315 [==============================] - 6s 2ms/step - loss: 10.8275 - mae: 0.8082 - val_loss: 14.6144 - val_mae: 0.9267
Epoch 47/50
3315/3315 [==============================] - 6s 2ms/step - loss: 10.8004 - mae: 0.8065 - val_loss: 14.8472 - val_mae: 0.8311
Epoch 48/50
3315/3315 [==============================] - 7s 2ms/step - loss: 10.8286 - mae: 0.8026 - val_loss: 14.7209 - val_mae: 0.8402
Epoch 49/50
3315/3315 [==============================] - 6s 2ms/step - loss: 10.7789 - mae: 0.8025 - val_loss: 14.8911 - val_mae: 0.8075
Epoch 50/50
3315/3315 [==============================] - 5s 2ms/step - loss: 10.7569 - mae: 0.7966 - val_loss: 15.2209 - val_mae: 0.8499
488/488 [==============================] - 1s 998us/step
Model Performance Metrics by Window Size:
Window Size    RMSE      MAE       MSE       R²
---------------------------------------------
1              3.4160    0.7919    11.6690   0.3525

In [11]:
test_data = pd.read_csv('test_stn+ef_label.csv')
test_data.head()

,stn4contest,ef_datetime,v01,v02,v03,v04,v05,v06,v07,v08,v09,year,month,day,hour,class_interval
0,31,2023-05-01 12:00:00,68.0,46.0,13.0,1.0,0.0,0.0,0.0,0.0,0.0,2023,5,1,12,NaN
1,31,2023-05-01 15:00:00,83.0,66.0,26.0,5.0,0.0,0.0,0.0,0.0,0.0,2023,5,1,15,NaN
2,31,2023-05-01 18:00:00,17.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2023,5,1,18,NaN
3,31,2023-05-01 21:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2023,5,1,21,NaN
4,31,2023-05-02 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2023,5,2,0,NaN

In [14]:
features = test_data[['ef_datetime', 'stn4contest', 'v01', 'v02', 'v03', 'v04', 'v05', 'v06', 'v07', 'v08', 'v09', 'year', 'month', 'day', 'hour']]
target = test_data['class_interval']

features.set_index('ef_datetime', inplace=True)

# 데이터 정렬
features = features.sort_index()

# 데이터 정규화
scaler_features = MinMaxScaler(feature_range=(0, 1))

test_features_scaled = scaler_features.fit_transform(features)

In [15]:
# 예측
test_predict = model.predict(test_features_scaled)

# 예측 결과를 데이터프레임으로 변환
predicted_df = pd.DataFrame(test_predict, index=features.index, columns=['Predicted vv'])

# 예측 결과 출력
predicted_df

204/204 [==============================] - 0s 1ms/step

                     Predicted vv
ef_datetime
2023-05-01 12:00:00      0.441448
2023-05-01 12:00:00     -0.241992
2023-05-01 12:00:00      2.584950
2023-05-01 12:00:00      1.929838
2023-05-01 12:00:00      0.820360
...                           ...
2023-10-10 21:00:00     25.348650
2023-10-10 21:00:00     39.113647
2023-10-10 21:00:00     41.733391
2023-10-10 21:00:00     31.216543
2023-10-10 21:00:00     23.040466

[6500 rows x 1 columns]

In [16]:
def get_class_interval(rainfall):
    if rainfall < 0.1:
        return 0
    elif 0.1 <= rainfall < 0.2:
        return 1
    elif 0.2 <= rainfall < 0.5:
        return 2
    elif 0.5 <= rainfall < 1.0:
        return 3
    elif 1.0 <= rainfall < 2.0:
        return 4
    elif 2.0 <= rainfall < 5.0:
        return 5
    elif 5.0 <= rainfall < 10.0:
        return 6
    elif 10.0 <= rainfall < 20.0:
        return 7
    elif 20.0 <= rainfall < 30.0:
        return 8
    else:
        return 9
    
# 'Predicted vv' 열에 변환 함수 적용
predicted_df['class_interval'] = predicted_df['Predicted vv'].apply(get_class_interval)

predicted_df['class_interval'].value_counts()

class_interval
0    1881
5     987
7     921
6     901
4     596
3     374
8     339
2     272
9     116
1     113
Name: count, dtype: int64

In [17]:
# 'Predicted vv' 열에 변환 함수 적용하여 클래스 구간 계산
predicted_df['Class Interval'] = predicted_df['Predicted vv'].apply(get_class_interval)

# 원래의 test_data에 'Class Interval' 열 추가
test_data['class_interval'] = predicted_df['Class Interval'].values

In [19]:
test_data.head()

,stn4contest,ef_datetime,v01,v02,v03,v04,v05,v06,v07,v08,v09,year,month,day,hour,class_interval
0,31,2023-05-01 12:00:00,68.0,46.0,13.0,1.0,0.0,0.0,0.0,0.0,0.0,2023,5,1,12,2
1,31,2023-05-01 15:00:00,83.0,66.0,26.0,5.0,0.0,0.0,0.0,0.0,0.0,2023,5,1,15,0
2,31,2023-05-01 18:00:00,17.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2023,5,1,18,5
3,31,2023-05-01 21:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2023,5,1,21,4
4,31,2023-05-02 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2023,5,2,0,3

In [20]:
submit = pd.read_csv("rainfall_test2.csv")
realsubmit = pd.read_csv("rainfall_test.csv")
prediction_test = test_data.copy()

#submit-prediction 지점,date 맞추기
prediction_test['ef_datetime'] = pd.to_datetime(prediction_test['ef_datetime'])
submit['ef_year_temp'] = submit['ef_year'].replace({'D': '2023'})
submit['ef_datetime'] = pd.to_datetime(submit[['ef_year_temp', 'ef_month', 'ef_day', 'ef_hour']].astype(str).agg('-'.join, axis=1), format='%Y-%m-%d-%H')
stn_mapping = {'STN031': 31, 'STN032': 32, 'STN033': 33, 'STN034': 34, 'STN035': 35}
submit['stn4contest'] = submit['stn4contest'].replace(stn_mapping)

#test_data['class_interval'] = y_pred2
#test_data['class_interval'] = test_data['class_interval'].apply(classify_class)

    
merged = submit.merge(prediction_test[['ef_datetime', 'stn4contest', 'class_interval']], 
                      on=['ef_datetime', 'stn4contest'], 
                      how='left', 
                      suffixes=('', '_pred'))
merged['class_interval_pred']
    
#-999 index 저장
idx999 = realsubmit[realsubmit['rainfall_test.class_interval'].notnull()].index
merged.loc[idx999, 'class_interval_pred'] = -999

# 제출용 데이터에 class_interval 채우기
realsubmit['rainfall_test.class_interval'] = merged['class_interval_pred']

#저장
realsubmit.to_csv("240494.csv")  
print(realsubmit.shape)
realsubmit.head()

(122000, 21)

,Unnamed: 0,rainfall_test.fc_year,rainfall_test.fc_month,rainfall_test.fc_day,rainfall_test.fc_hour,rainfall_test.stn4contest,rainfall_test.dh,rainfall_test.ef_year,rainfall_test.ef_month,rainfall_test.ef_day,...,rainfall_test.v01,rainfall_test.v02,rainfall_test.v03,rainfall_test.v04,rainfall_test.v05,rainfall_test.v06,rainfall_test.v07,rainfall_test.v08,rainfall_test.v09,rainfall_test.class_interval
0,1,D,5,1,9,STN031,3,D,5,1,...,68,46,13,1,0,0,0,0,0,2
1,2,D,5,1,9,STN031,6,D,5,1,...,83,66,26,5,0,0,0,0,0,0
2,3,D,5,1,9,STN031,9,D,5,1,...,17,6,0,0,0,0,0,0,0,5
3,4,D,5,1,9,STN031,12,D,5,1,...,0,0,0,0,0,0,0,0,0,4
4,5,D,5,1,9,STN031,15,D,5,2,...,0,0,0,0,0,0,0,0,0,3

## MLP에 레이어 추가

In [26]:
# 학습 데이터와 테스트 데이터 분할
train_data = train[train['stn4contest'] <= 16]
test_data = train[train['stn4contest'] > 15]

# 입력 특성 (v01 ~ v09)와 타겟 변수 (vv) 분리
X_train = train_data[['stn4contest', 'year', 'month', 'day', 'hour', 'v01', 'v02', 'v03', 'v04', 'v05', 'v06', 'v07', 'v08', 'v09']]
y_train = train_data['vv']
X_test = test_data[['stn4contest', 'year', 'month', 'day', 'hour', 'v01', 'v02', 'v03', 'v04', 'v05', 'v06', 'v07', 'v08', 'v09']]
y_test = test_data['vv']

# 데이터 표준화
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [29]:
# MLP 모델 정의
model_comp = Sequential([
    Dense(128, input_dim=14, activation='relu'),  # 입력층
    Dropout(0.3),  # 드롭아웃 추가
    Dense(64, activation='relu'),  # 첫 번째 은닉층
    Dropout(0.3),  # 드롭아웃 추가
    Dense(32, activation='relu'),  # 두 번째 은닉층
    Dropout(0.3),  # 드롭아웃 추가
    Dense(16, activation='relu'),  # 세 번째 은닉층 추가
    Dropout(0.3),  # 드롭아웃 추가
    Dense(1, activation='linear')  # 출력층
])

# 모델 컴파일
model_comp.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

# 모델 학습
model_comp.fit(X_train, y_train, epochs=50, batch_size=16, validation_split=0.2)

# 모델 예측
y_pred = model_comp.predict(X_test)

Epoch 1/50
3315/3315 [==============================] - 6s 2ms/step - loss: 13.3013 - mae: 0.9227 - val_loss: 16.4329 - val_mae: 0.8227
Epoch 2/50
3315/3315 [==============================] - 5s 2ms/step - loss: 12.6247 - mae: 0.9039 - val_loss: 16.9464 - val_mae: 0.8660
Epoch 3/50
3315/3315 [==============================] - 6s 2ms/step - loss: 12.2278 - mae: 0.9097 - val_loss: 16.3510 - val_mae: 0.8804
Epoch 4/50
3315/3315 [==============================] - 6s 2ms/step - loss: 12.5355 - mae: 0.9222 - val_loss: 15.6146 - val_mae: 0.8740
Epoch 5/50
3315/3315 [==============================] - 6s 2ms/step - loss: 12.1419 - mae: 0.9190 - val_loss: 16.0999 - val_mae: 0.9786
Epoch 6/50
3315/3315 [==============================] - 6s 2ms/step - loss: 12.1705 - mae: 0.9284 - val_loss: 15.9957 - val_mae: 0.8642
Epoch 7/50
3315/3315 [==============================] - 6s 2ms/step - loss: 12.1992 - mae: 0.9271 - val_loss: 15.7135 - val_mae: 0.9141
Epoch 8/50
3315/3315 [==============================] - 6s 2ms/step - loss: 12.0627 - mae: 0.9232 - val_loss: 15.0193 - val_mae: 0.9357
Epoch 9/50
3315/3315 [==============================] - 6s 2ms/step - loss: 12.2149 - mae: 0.9305 - val_loss: 14.8491 - val_mae: 0.8983
Epoch 10/50
3315/3315 [==============================] - 6s 2ms/step - loss: 12.1316 - mae: 0.9319 - val_loss: 16.4101 - val_mae: 0.8875
Epoch 11/50
3315/3315 [==============================] - 7s 2ms/step - loss: 12.1696 - mae: 0.9383 - val_loss: 15.6136 - val_mae: 0.8810
Epoch 12/50
3315/3315 [==============================] - 7s 2ms/step - loss: 11.8570 - mae: 0.9315 - val_loss: 15.9608 - val_mae: 0.9002
Epoch 13/50
3315/3315 [==============================] - 9s 3ms/step - loss: 12.1733 - mae: 0.9317 - val_loss: 15.1496 - val_mae: 0.9233
Epoch 14/50
3315/3315 [==============================] - 8s 2ms/step - loss: 12.1956 - mae: 0.9410 - val_loss: 14.9672 - val_mae: 0.9239
Epoch 15/50
3315/3315 [==============================] - 7s 2ms/step - loss: 12.0474 - mae: 0.9372 - val_loss: 16.0703 - val_mae: 0.8897
Epoch 16/50
3315/3315 [==============================] - 7s 2ms/step - loss: 12.2171 - mae: 0.9508 - val_loss: 15.5229 - val_mae: 0.9009
Epoch 17/50
3315/3315 [==============================] - 6s 2ms/step - loss: 12.1054 - mae: 0.9360 - val_loss: 15.1284 - val_mae: 0.9184
Epoch 18/50
3315/3315 [==============================] - 7s 2ms/step - loss: 12.0270 - mae: 0.9308 - val_loss: 15.5295 - val_mae: 1.0215
Epoch 19/50
3315/3315 [==============================] - 7s 2ms/step - loss: 12.1096 - mae: 0.9421 - val_loss: 16.6280 - val_mae: 0.8704
Epoch 20/50
3315/3315 [==============================] - 7s 2ms/step - loss: 11.9173 - mae: 0.9408 - val_loss: 15.0983 - val_mae: 0.9293
Epoch 21/50
3315/3315 [==============================] - 8s 2ms/step - loss: 11.9921 - mae: 0.9429 - val_loss: 15.9184 - val_mae: 0.8336
Epoch 22/50
3315/3315 [==============================] - 6s 2ms/step - loss: 12.1439 - mae: 0.9466 - val_loss: 15.0909 - val_mae: 0.8795
Epoch 23/50
3315/3315 [==============================] - 7s 2ms/step - loss: 12.0563 - mae: 0.9490 - val_loss: 15.1792 - val_mae: 0.8889
Epoch 24/50
3315/3315 [==============================] - 8s 2ms/step - loss: 11.9464 - mae: 0.9315 - val_loss: 15.9506 - val_mae: 0.8657
Epoch 25/50
3315/3315 [==============================] - 7s 2ms/step - loss: 11.9193 - mae: 0.9375 - val_loss: 16.0011 - val_mae: 0.8309
Epoch 26/50
3315/3315 [==============================] - 7s 2ms/step - loss: 12.1664 - mae: 0.9464 - val_loss: 15.3439 - val_mae: 0.8764
Epoch 27/50
3315/3315 [==============================] - 6s 2ms/step - loss: 11.9031 - mae: 0.9326 - val_loss: 15.7682 - val_mae: 1.0628
Epoch 28/50
3315/3315 [==============================] - 7s 2ms/step - loss: 11.7922 - mae: 0.9307 - val_loss: 14.5490 - val_mae: 0.9741
Epoch 29/50
3315/3315 [==============================] - 6s 2ms/step - loss: 12.0528 - mae: 0.9321 - val_loss: 15.4640 - val_mae: 0.9227
Epoch 30/50
3315/3315 [==============================] - 7s 2ms/step - loss: 12.0691 - mae: 0.9390 - val_loss: 15.4010 - val_mae: 0.9797
Epoch 31/50
3315/3315 [==============================] - 6s 2ms/step - loss: 12.1465 - mae: 0.9330 - val_loss: 14.7764 - val_mae: 1.0098
Epoch 32/50
3315/3315 [==============================] - 6s 2ms/step - loss: 12.0025 - mae: 0.9336 - val_loss: 15.8710 - val_mae: 0.8859
Epoch 33/50
3315/3315 [==============================] - 7s 2ms/step - loss: 12.1116 - mae: 0.9416 - val_loss: 15.4379 - val_mae: 0.8731
Epoch 34/50
3315/3315 [==============================] - 7s 2ms/step - loss: 11.9313 - mae: 0.9397 - val_loss: 15.3710 - val_mae: 0.9127
Epoch 35/50
3315/3315 [==============================] - 6s 2ms/step - loss: 12.0115 - mae: 0.9482 - val_loss: 16.4021 - val_mae: 1.1587
Epoch 36/50
3315/3315 [==============================] - 6s 2ms/step - loss: 12.0611 - mae: 0.9510 - val_loss: 15.5071 - val_mae: 0.9569
Epoch 37/50
3315/3315 [==============================] - 7s 2ms/step - loss: 11.9022 - mae: 0.9539 - val_loss: 15.9197 - val_mae: 1.0229
Epoch 38/50
3315/3315 [==============================] - 7s 2ms/step - loss: 12.1577 - mae: 0.9570 - val_loss: 16.0119 - val_mae: 1.0104
Epoch 39/50
3315/3315 [==============================] - 7s 2ms/step - loss: 12.1010 - mae: 0.9529 - val_loss: 15.8015 - val_mae: 0.9054
Epoch 40/50
3315/3315 [==============================] - 8s 2ms/step - loss: 11.9026 - mae: 0.9568 - val_loss: 15.0751 - val_mae: 0.9549
Epoch 41/50
3315/3315 [==============================] - 7s 2ms/step - loss: 11.7767 - mae: 0.9501 - val_loss: 15.4456 - val_mae: 0.9468
Epoch 42/50
3315/3315 [==============================] - 7s 2ms/step - loss: 12.0459 - mae: 0.9426 - val_loss: 15.9645 - val_mae: 0.8760
Epoch 43/50
3315/3315 [==============================] - 7s 2ms/step - loss: 11.9388 - mae: 0.9437 - val_loss: 15.6220 - val_mae: 0.9008
Epoch 44/50
3315/3315 [==============================] - 7s 2ms/step - loss: 12.0584 - mae: 0.9563 - val_loss: 16.2752 - val_mae: 0.9690
Epoch 45/50
3315/3315 [==============================] - 8s 2ms/step - loss: 12.1568 - mae: 0.9504 - val_loss: 15.4683 - val_mae: 0.9995
Epoch 46/50
3315/3315 [==============================] - 8s 2ms/step - loss: 11.9720 - mae: 0.9452 - val_loss: 14.9617 - val_mae: 0.9621
Epoch 47/50
3315/3315 [==============================] - 9s 3ms/step - loss: 11.8554 - mae: 0.9394 - val_loss: 15.0422 - val_mae: 0.7842
Epoch 48/50
3315/3315 [==============================] - 7s 2ms/step - loss: 11.9762 - mae: 0.9422 - val_loss: 15.7646 - val_mae: 0.9614
Epoch 49/50
3315/3315 [==============================] - 7s 2ms/step - loss: 11.9380 - mae: 0.9401 - val_loss: 15.6678 - val_mae: 0.8961
Epoch 50/50
3315/3315 [==============================] - 8s 2ms/step - loss: 11.8357 - mae: 0.9256 - val_loss: 15.3128 - val_mae: 0.8735
488/488 [==============================] - 1s 2ms/step

In [27]:
y_pred.shape

(6500, 1)

In [28]:
y_test.shape

(15600,)

In [30]:
# 성능 지표 계산
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# 결과 저장
results = {
    'Window Size': 1,  # 현재 예제에서는 window size가 1로 고정되어 있음
    'RMSE': rmse,
    'MAE': mae,
    'MSE': mse,
    'R²': r2
}

# 결과 출력
print("Model Performance Metrics by Window Size:")
print(f"{'Window Size':<15}{'RMSE':<10}{'MAE':<10}{'MSE':<10}{'R²':<10}")
print(f"{'-'*45}")
print(f"{results['Window Size']:<15}{results['RMSE']:<10.4f}{results['MAE']:<10.4f}{results['MSE']:<10.4f}{results['R²']:<10.4f}")

Model Performance Metrics by Window Size:
Window Size    RMSE      MAE       MSE       R²
---------------------------------------------
1              3.4188    0.8144    11.6884   0.3514